version: '3.8'
services:
  backend:  
    build: ./Backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/Parkini
    volumes:
      - ./Backend:/app
      - /app/node_modules

  frontend:  
    build: ./Front-end-Front-Office-  
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
